### ISSUE TITLE
place dot before last quote

### ISSUE THREAD

**Issue by A** [matmuchrapna/Another-Typography-Tool#3]
«dependency hell.»

**Comment by iamstarkov** [comment]
wat? what’s the issue?

**Comment by A** [comment]
Just case to test

**Comment by iamstarkov** [comment]
![dune-ii-7](https://cloud.githubusercontent.com/assets/559321/7128696/3289706e-e256-11e4-8d31-ae97211e0373.jpg)
Milord, we need more information!

**Comment by iamstarkov** [comment]
we have an textr now =)
